// Code generated by stringer; DO NOT EDIT.
// timestamp: 2024-10-13 06:56:57.988134299 +0100 WAT m=+0.000710180

package project

import "fmt"

func (v Robot) String() string {
	return fmt.Sprintf("Robot: {  Name: %s,  uuid: %s,  model: %s }", v.Name, v.uuid, v.model)
}
