// Code generated by stringer; DO NOT EDIT.
// timestamp: 2024-10-13 06:56:57.987892545 +0100 WAT m=+0.000468426

package main

import "fmt"

func (v Lony) String() string {
	return fmt.Sprintf("Lony: {  Benjamin: %s,  cadet: %s,  val: %s,  superhero: %s }", v.Benjamin, v.cadet, v.val, v.superhero)
}
