// Code generated by stringer; DO NOT EDIT.
// timestamp: 2024-10-13 06:56:57.988311977 +0100 WAT m=+0.000887858

package main

import "fmt"

func (v Person) String() string {
	return fmt.Sprintf("Person: {  Name: %s,  Age: %s,  City: %s,  Country: %s }", v.Name, v.Age, v.City, v.Country)
}

func (v Shop) String() string {
	return fmt.Sprintf("Shop: {  Employees: %s,  Manager: %s,  Address: %s,  YearlyRevenue: %s }", v.Employees, v.Manager, v.Address, v.YearlyRevenue)
}

func (v Family) String() string {
	return fmt.Sprintf("Family: {  Parent: %s,  Childreen: %s,  House: %s }", v.Parent, v.Childreen, v.House)
}
